# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c30bb2806a8adbc1e7544d32e73ee3af32927829b35ec5433b5897d16c7a29bd373818903969e6e0efdf3ecdf0277960007d9751ac93a8c28f5d7836320fecc

test:
  secret_key_base: 34ee8ef4115fc6f22d600457ff5f90375ad03e1ff53b9a0c74d97081c2f598fdfd2d15af1db6621923835f2a88687ce3567f9a188561283643bac24c5491215a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
